# Generated by Django 4.2.7 on 2024-07-20 14:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="Invalid Phone Number",
                                message="Enter Valid Phone Number",
                                regex="07\\d\\d\\d\\d\\d\\d\\d\\d",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField()),
                ("identity_no", models.CharField(max_length=12)),
                ("box_ca_number", models.CharField(max_length=16, unique=True)),
                ("customer_number", models.CharField(max_length=5, unique=True)),
                ("active_connection", models.BooleanField(default=True)),
                ("has_digital_box", models.BooleanField(default=True)),
                ("offer_power_intake", models.BooleanField(default=False)),
                ("under_repair", models.BooleanField(default=False)),
                (
                    "connection_start_date",
                    models.DateField(
                        default=datetime.datetime(
                            2024,
                            7,
                            20,
                            14,
                            36,
                            21,
                            441680,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="common.area"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="Invalid Phone Number",
                        message="Enter Valid Phone Number",
                        regex="07\\d\\d\\d\\d\\d\\d\\d\\d",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "amount",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Value has to be a positive number"
                            )
                        ]
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="common.customer",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="common.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "amount",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Value has to be a positive number"
                            )
                        ]
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="common.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="common.employee"
            ),
        ),
    ]
