# Generated by Django 4.2.7 on 2024-11-09 05:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_area_collection_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="customer",
        ),
        migrations.AlterField(
            model_name="customer",
            name="connection_start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 9, 5, 42, 56, 818813, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="CustomerConnection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="common.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="connection",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                to="common.customerconnection",
            ),
            preserve_default=False,
        ),
    ]
