# Generated by Django 4.2.7 on 2024-11-09 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_remove_payment_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerconnection",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="connection_start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 9, 5, 52, 47, 828777, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
