# Generated by Django 4.2.7 on 2025-01-10 05:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_customerconnection_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="customer",
        ),
        migrations.AddField(
            model_name="bill",
            name="connection",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                to="common.customerconnection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customerconnection",
            name="box_ca_number",
            field=models.CharField(default="0", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customerconnection",
            name="start_date",
            field=models.DateField(auto_now_add=True, default="2024-11-09"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="connection_start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 10, 5, 11, 2, 366888, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
