# Generated by Django 4.2.7 on 2025-01-10 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_remove_bill_customer_bill_connection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="box_ca_number",
        ),
        migrations.AlterField(
            model_name="customer",
            name="connection_start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 10, 5, 17, 5, 386875, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customerconnection",
            name="box_ca_number",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
