# Generated by Django 4.2.7 on 2025-01-10 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_remove_customer_box_ca_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="description",
            field=models.TextField(
                choices=[
                    ("Monthly Bill", "Monthly"),
                    ("Zero value Bill while Disconnection", "Zero Disconnection"),
                    ("Zero value Bill while reconnection", "Zero Reconnection"),
                ],
                default="Monthly Bill",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="connection_start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 10, 7, 14, 29, 262167, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
